---
  - name: restart bind
    become: yes
    become_user: root
    service:
      name: named
      state: restarted

  - name: reload bind
    become: yes
    become_user: root
    service:
      name: named
      state: reloaded

